CREATE table "PROFESSOR" (
    "NIF_PROF"            NUMBER(9) NOT NULL,
    "NOME_PROPRIO"         VARCHAR2(50) NOT NULL,
    "NOME_APELIDO"         VARCHAR2(50) NOT NULL,
    "DATA_NASCIMENTO_PROF" DATE NOT NULL,
    "CATEGORIA"            VARCHAR2(50) NOT NULL,
    constraint  "PROFESSOR_PK" primary key ("NIF_PROF")
);

CREATE table "DEPARTAMENTO" (
    "NUM_DEP"    NUMBER(20) NOT NULL,
	"NIF_PROF"		NUMBER(9) NOT NULL,
    "NOME_DEP"   VARCHAR2(50) NOT NULL UNIQUE,
	-- Restrição de Integridade
	-- a. Não deve haver duplicações de nomes do departamento.
    "ESCRITÓRIO" VARCHAR2(50) NOT NULL,
	-- Restrição de Integridade
	-- b. O escritório principal onde está localizado o departamento não pode ter valor nulo.
	"TEMPO"		NUMBER(6) NOT NULL,
    constraint  "DEPARTAMENTO_PK" primary key ("NUM_DEP")
);

CREATE table "ESTUDANTE" (
    "NIF_EST"          NUMBER(9) NOT NULL,
	"NUM_DEP" 			NUMBER(20) NOT NULL,
    "NOME"                VARCHAR2(50) NOT NULL,
    "DATA_NASCIMENTO_EST" DATE NOT NULL,
    "CURSO"               VARCHAR2(50) NOT NULL,
    constraint  "ESTUDANTES_PK" primary key ("NIF_EST")
);

CREATE table "PROJETO" (
    "NUM_ID"               NUMBER(20) NOT NULL,
	"NIF_PROF" 			NUMBER(9) NOT NULL,
    "DATA_INICIO"          DATE NOT NULL,
    "DATA_FIM"             DATE,
    constraint  "PROJETO_PK" primary key ("NUM_ID"),
	constraint	"PROJETO_CHECK" CHECK (DATA_FIM>DATA_INICIO)
	-- Restrição de Integridade
	-- c. Deve haver uma validação nas datas do projeto, ou seja, a data que indica o final do projeto
	-- não pode ser anterior a data onde o projeto inicia.
);

CREATE TABLE "ESPECIALIDADE" (
	"NIF_PROF"			NUMBER(9) NOT NULL,
	"ESPECIALIDADE"		VARCHAR2(50) NOT NULL
);

CREATE TABLE "PROFESSOR_TRABALHA_PROJETO" (
	"NIF_PROF"			NUMBER(9) NOT NULL,
	"NUM_ID"			NUMBER(20) NOT NULL
);

CREATE TABLE "PROF_TRABALHA_DEP" (
	"NIF_PROF"			NUMBER(9) NOT NULL,
	"NUM_DEP"			NUMBER(20) NOT NULL,
	"TEMPO" 			NUMBER(6) NOT NULL
);

CREATE TABLE "PROFESSOR_SUPERVISIONA_REL" (
	"NIF_PROF"			NUMBER(9) NOT NULL,
	"NUM_ID" 			NUMBER(20) NOT NULL,
	"NIF_EST"			NUMBER(9) NOT NULL
);

CREATE TABLE "ACONSELHA" (
	"NIF_CONSELHADOR"	NUMBER(9) NOT NULL,
	"NIF_EST"			NUMBER(9) NOT NULL,
	constraint  "ACONSELHA_PK" primary key ("NIF_CONSELHADOR")
);

CREATE TABLE "ORGANISMO_FINANCIADOR" (
	"NUM_ID"		NUMBER(20) NOT NULL,
	"ORÇAMENTO"		NUMBER(20) NOT NULL,
	constraint  "NUM_ID_PK" primary key ("NUM_ID")
);

CREATE TABLE "TELEFONE" (
	"NIF_EST" 				NUMBER(9) NOT NULL,
	"NUM_TELEFONE"			NUMBER(20) NOT NULL,
	constraint  "TELEFONE_PK" primary key ("NIF_EST")
);

-- ALTERAÇÕES TABELAS DE RELAÇÕES

ALTER TABLE "ESPECIALIDADE" ADD CONSTRAINT "FK1" FOREIGN KEY ("NIF_PROF")
	  REFERENCES  "PROFESSOR" ("NIF_PROF") ENABLE
;

ALTER TABLE "PROFESSOR_TRABALHA_PROJETO" ADD CONSTRAINT "FK2" FOREIGN KEY ("NIF_PROF")
	  REFERENCES  "PROFESSOR" ("NIF_PROF") ENABLE
;

ALTER TABLE "PROFESSOR_TRABALHA_PROJETO" ADD CONSTRAINT "FK3" FOREIGN KEY ("NUM_ID")
	  REFERENCES  "PROJETO" ("NUM_ID") ENABLE
;

ALTER TABLE "PROF_TRABALHA_DEP" ADD CONSTRAINT "FK4" FOREIGN KEY ("NIF_PROF")
	  REFERENCES  "PROFESSOR" ("NIF_PROF") ENABLE
;

ALTER TABLE "PROF_TRABALHA_DEP" ADD CONSTRAINT "FK5" FOREIGN KEY ("NUM_DEP")
	  REFERENCES  "DEPARTAMENTO" ("NUM_DEP") ENABLE
;

ALTER TABLE "PROFESSOR_SUPERVISIONA_REL" ADD CONSTRAINT "FK6" FOREIGN KEY ("NIF_PROF")
	  REFERENCES  "PROFESSOR" ("NIF_PROF") ENABLE
;

ALTER TABLE "PROFESSOR_SUPERVISIONA_REL" ADD CONSTRAINT "FK7" FOREIGN KEY ("NUM_ID")
	  REFERENCES  "PROJETO" ("NUM_ID") ENABLE
;

ALTER TABLE "PROFESSOR_SUPERVISIONA_REL" ADD CONSTRAINT "FK8" FOREIGN KEY ("NIF_EST")
	  REFERENCES  "ESTUDANTE" ("NIF_EST") ENABLE
;

ALTER TABLE "ACONSELHA" ADD CONSTRAINT "FK9" FOREIGN KEY ("NIF_EST")
	  REFERENCES  "ESTUDANTE" ("NIF_EST") ENABLE
;

ALTER TABLE "TELEFONE" ADD CONSTRAINT "FK10" FOREIGN KEY ("NIF_EST")
	  REFERENCES  "ESTUDANTE" ("NIF_EST") ENABLE
;

ALTER TABLE "ORGANISMO_FINANCIADOR" ADD CONSTRAINT "FK11" FOREIGN KEY ("NUM_ID")
	  REFERENCES  "PROJETO" ("NUM_ID") ENABLE
;

--ALTERAÇOES TABELAS NORMAIS

ALTER TABLE "PROJETO" ADD CONSTRAINT "FK12" FOREIGN KEY ("NIF_PROF")
	  REFERENCES  "PROFESSOR" ("NIF_PROF") ENABLE
;

ALTER TABLE "DEPARTAMENTO" ADD CONSTRAINT "FK13" FOREIGN KEY ("NIF_PROF")
	  REFERENCES  "PROFESSOR" ("NIF_PROF") ENABLE
;

ALTER TABLE "ESTUDANTE" ADD CONSTRAINT "FK14" FOREIGN KEY ("NUM_DEP")
	  REFERENCES  "DEPARTAMENTO" ("NUM_DEP") ENABLE
;

-- Restrições de Integridade - Triggers
-- d. Um professor não pode supervisionar mais de três projetos.
CREATE OR REPLACE TRIGGER "ERRO_SUPERVISAO"
BEFORE INSERT OR UPDATE ON "PROFESSOR_TRABALHA_PROJETO"
FOR EACH ROW
DECLARE
NUM_CONT INTEGER;
BEGIN
SELECT * INTO NUM_CONT FROM (SELECT COUNT(*) FROM PROFESSOR_TRABALHA_PROJETO WHERE PROFESSOR_TRABALHA_PROJETO.NIF_PROF =: new.NIF_PROF);
IF (NUM_CONT >= 3) THEN
RAISE_APPLICATION_ERROR(-20010, 'ERRO - Um professor não pode gerir mais de três projetos');
END IF;
END;
/  